LOCAL_PATH := $(DEVICE_PATH)

#GCam
include $(CLEAR_VARS)
LOCAL_MODULE := GCamMGC
LOCAL_SRC_FILES := prebuilt/priv-app/GCamMGC/GCamMGC.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_OVERRIDES_PACKAGES := Snap Camera2
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
